### ISSUE TITLE
makeupRouter.js

### ISSUE THREAD

**Issue by matcoco** [SophieTopart/WCS_AtelierExpress#1]
Bravo ! l'ensemble fonctionne très bien, cependant, je te propose quelques améliorations (à valider avec Katalina =) )
- le require('Joi') le mettre tout en haut du fichier par convention et ça permet de savoir les packages utilisés.
- j'ai réussi à ajouter un 'product' dont le nom pouvait être n'importe quel type de donnée et ajouter un prix négatif. J'ai donc utilisé Joi pour ajouter de la validation
- Concernant la validation, on peut imaginer créer une fonction "validationDataProductPrice(req, res)", comme on pourrait l'utiliser 2 fois, ça éviterait la répétition de code.
```
const  validationDataProductPrice= (req, res) => {
    const { error: validationErrors } = Joi.object({
        product: Joi.string().max(255),
        price: Joi.number().min(0)
    }).validate(req.body, { abortEarly: false })

    if (validationErrors)
        return res.status(422).json({ errors: validationErrors.details })
}
```
```
router.post('/', (req, res) => {
    const { product, price } = req.body

    validationDataProductPrice(req, res);
    let sql = 'INSERT INTO makeup(product, price) VALUES (?, ?)'
    connection.promise()
        .query(sql, [product, price])
        .then(([result]) => {
            const createdProduct = { id: result.insertId, product, price }
            res.json(createdProduct)
        })
        .catch((err) => {
            console.error(err)
            res.status(500).send('Error adding makeup product')
        })
})
```

**Comment by SophieTopart** [comment]
Mathieu, merci de ce retour. Cette technique fonctionne très bien pour détecter les erreurs, cependant en l'état, ça me signale qu'il y a une erreur, mais ça ajoute quand même le produit ! J'ai remis l'occurence en entier avec un if / else, et ça fonctionne correctement.
J'essaie de trouver le moyen d'ajouter une constante pour ne pas me répéter...

**Comment by matcoco** [comment]
😅 mince ! merci pour ton retour ! du coup je me suis penché sur le problème. Normalement, c'est patché .
L'idée est de retourner le resultat de la fonction validationProductPrice()
Si on me retourne validationErrors.error ( c'est a dire un object qui contient une clé error) je continue pas sinon je passe à la suite .
```
const validationProductPrice = (req, res) => {
    return { error: validationErrors } = Joi.object({
        product: Joi.string().max(255),
        price: Joi.number().min(0)
    }).validate(req.body, { abortEarly: false })
}

router.post('/', (req, res) => {
    const { product, price } = req.body

    const validationErrors = validationProductPrice(req, res);

    if (validationErrors.error) {
        res.status(422).json({ errors: validationErrors.error })
    } else {
        let sql = 'INSERT INTO makeup(product, price) VALUES (?, ?)'
        connection.promise()
            .query(sql, [product, price])
            .then(([result]) => {
                const createdProduct = { id: result.insertId, product, price }
                res.json(createdProduct)
            })
            .catch((err) => {
                console.error(err)
                res.status(500).send('Error adding makeup product')
            })
    }
})
```

**Comment by SophieTopart** [comment]
Super, merci, cette subtilité m'avait échappé !
